<a href="https://colab.research.google.com/github/sun-in-universe/blue_dot/blob/main/CNN_%EC%86%8C%EA%B0%9C_%EB%B0%8F_MNIST_%EA%B5%AC%ED%98%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
#1-16값이 들어간 4*4 배열에 대해, 풀링 크기 2, 스트라이드 크기 2로 최대 풀링 수행하기

import tensorflow as tf
import numpy as np

x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(x)

#4차원 배열로 변환
x = x.reshape(1, 4, 4, 1)
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[[[ 1]
   [ 2]
   [ 3]
   [ 4]]

  [[ 5]
   [ 6]
   [ 7]
   [ 8]]

  [[ 9]
   [10]
   [11]
   [12]]

  [[13]
   [14]
   [15]
   [16]]]]


In [43]:
# tf.nn은 TensorFlow 라이브러리에서 제공하는 모든 뉴럴 네트워크 관련 연산들이 모여 있는 서브 패키지(subpackage)
p_out = tf.nn.max_pool2d(x, ksize=2, strides=2, padding='VALID')
p_out.numpy().reshape(2, 2)

array([[ 6.,  8.],
       [14., 16.]], dtype=float32)

In [44]:
import tensorflow as tf
import numpy as np

x = np.array([-1, 2, -3, 4, -5])
r_out = tf.nn.relu(x)
r_out.numpy()

array([0, 2, 0, 4, 0])

In [45]:
'''# reshape(변수의 개수) -> 차원을 결정한다. 개수, z, y, x
# x, y를 4차원으로 변환

import tensorflow as tf
x_4d = x.astype(np.float).reshape(1, 3, 3, 1)
w_4d = w.reshape(2, 2, 1, 1,)'''

'# reshape(변수의 개수) -> 차원을 결정한다. 개수, z, y, x\n# x, y를 4차원으로 변환 \n\nimport tensorflow as tf\nx_4d = x.astype(np.float).reshape(1, 3, 3, 1)\nw_4d = w.reshape(2, 2, 1, 1,)'

4x4x10 구조를 가질때, 3x3 크기의 가중치를 적용할 경우, 가중치 배열 크기는 3x3x10 하지만 여러 채널을 가지는 이미지도 가능합니다 => 채널의 크기가 10개일 수도 있다. 컬러이미지가 아니라 다른 특성을 가진 채널이 있을 수 있다.=> 특성맵은 2x2x10이 되겠죵.

특성맵은 사람이 정해주는 하이퍼파라미터입니다!

커널의 크기, 형태, 개수는 CNN 모델의 아키텍처를 설계하는 중요한 하이퍼파라미터!

패션 mnist로 CNN하기

In [46]:
import tensorflow as tf
!pip install --upgrade tensorflow

(X_train_all, y_train_all), (X_test, y_test) = tf.keras.datasets.fashion_mnist.load_data()
print(X_train_all.shape, y_train_all.shape)

(60000, 28, 28) (60000,)


In [47]:
# 훈련데이터셋과 검증데이터셋을 구분
from sklearn.model_selection import train_test_split

x_train, x_val, y_train, y_val = train_test_split(X_train_all, y_train_all, stratify=y_train_all, test_size=0.2, random_state=42)

print(x_train.shape, x_val.shape)
print(y_train.shape, y_val.shape)

(48000, 28, 28) (12000, 28, 28)
(48000,) (12000,)


In [48]:
# 타깃을 원-핫 인코딩으로 변환하기

y_train_encoded = tf.keras.utils.to_categorical(y_train)
y_val_encoded = tf.keras.utils.to_categorical(y_val)

print(y_train_encoded.shape, y_val_encoded.shape)
print(y_train[0], y_train_encoded[0])
print(y_val[0], y_val_encoded[0])

(48000, 10) (12000, 10)
6 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
5 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [49]:
# -1을 통해서 첫번째 차원을 자동으로 설정, 흑백 이미지이므로
x_train = x_train.reshape(-1, 28, 28, 1)
x_val = x_val.reshape(-1, 28, 28, 1)

x_train.shape
print(x_train)

[[[[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  ...

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]]


 [[[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  ...

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]]


 [[[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  ...

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]]


 ...


 [[[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]

In [50]:
# 입력 데이터 표준화하기 전처리 하기

print(x_train[0][0])

x_train = x_train / 255
x_val = x_val / 255

print(x_train[0][0])

[[ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 1]
 [ 1]
 [ 0]
 [ 0]
 [ 0]
 [25]
 [55]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [43]
 [24]
 [ 0]
 [ 0]
 [ 0]
 [ 1]
 [ 0]
 [ 0]
 [ 0]
 [ 0]
 [ 0]]
[[0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.00392157]
 [0.00392157]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.09803922]
 [0.21568627]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.16862745]
 [0.09411765]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.00392157]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]]


In [51]:
# CNN에 필요한 클래스 임포트하기

from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

AssertionError: ignored

In [ ]:
# 합성곱 층 쌓기
# 1. 합성곱 가중치 개수, 2. 합성곱 가중치 크기(높이, 너비)튜플
# 3. 활성화 함수, 4. 패딩, 5. 입력 크기

conv1 = tf.keras.Sequential()
conv1.add(Conv2D(10, (3,3), activation='relu', padding='same', input_shape=(28, 28, 1)))

In [ ]:
# 풀링층 쌓기
# 1. 풀링의 (높이, 너비)튜플, 2. 스트라이드
conv1.add(MaxPooling2D((2, 2)))

In [ ]:
# Flatten 클래스 사용, 일렬로 펼침
conv1.add(Flatten())

In [ ]:
#완전 연결층 쌓기
#첫번째 연결층 = 100개 뉴런, 마지막 출력층 = 10개의 뉴런

conv1.add(Dense(100, activation='relu'))
conv1.add(Dense(10, activation='softmax'))

In [ ]:
conv1.summary()

In [ ]:
print(x_train.shape)
print(y_train_encoded.shape)
print(x_val.shape)
print(y_val_encoded.shape)

In [ ]:
# CNN 모델 훈련하기
conv1.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
history = conv1.fit(x_train, y_train_encoded, epochs=10, validation_data = (x_val, y_val_encoded))

In [ ]:
import matplotlib.pyplot as plt

plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])

plt.ylabel('loss')
plt.xlabel('epoch')
# 범례를 추가하는 plt.legend
plt.legend(['train_loss', 'val_loss'])

plt.show()

In [ ]:
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])

plt.ylabel('accuracy')
plt.xlabel('epoch')
# 범례를 추가하는 plt.legend
plt.legend(['train_accuracy', 'val_accuracy'])

plt.show()